export const CLASS_NAMES = {
  webCodeEditor: "web-code-editor",
  pane1: "pane1",
  pane2: "pane2",
  pane3: "pane3",
  active: "active",
  editorContainer: "editor-container",
  editorTextarea: "editor-textarea",
  titleTabs: "title-tabs",
  customCodeMirror: "custom-codeMirror",
  createTab: "item",
  tabCloseIcon: "close-icon",
  dirOpen: "open",
  mask: "mask",
  createMenu: "item create",
  rightMenu: "right-menu",
  rightMenuDivide: "divide",
  rightMenuItem: "item",
  fileMenuItem: "item",
  dirMenuItem: "item dir",
  errMsg: "msg",
  inputMenuField: "field",
  dirFiles: "files",
  imageContainer: "image-container",
  image: "image",
  openDirBtn: "open-dir-btn",
  isInvalid: "new-is-invalid",
};

export const STATIC_TEXT = {
  openFolder: "打开文件夹",
  selectFolder: "选择文件夹",
  close: "关闭",
  closeAll: "全部关闭",
  closeOther: "全部其它",
  closeRight: "关闭到右侧",
  openRight: "右侧打开",
  delete: "删除",
  newFile: "新建文件",
  newDir: "新建文件夹",
  errMeg: "必须提供文件或文件名",
  save: "保存",
};
